# Generated by Django 3.0.7 on 2020-06-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='type',
            new_name='utility_type',
        ),
    ]
