# Generated by Django 3.0.8 on 2020-07-07 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0023_auto_20200701_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_amount', models.FloatField()),
                ('applied_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone_number', models.CharField(max_length=15)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('credits', models.FloatField(blank=True, null=True)),
                ('late_fee_exemption', models.DateField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='TenantCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('bill_period_end_date', models.DateField()),
                ('due_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')])),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantChargePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
                ('tenant_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TenantCharge')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='charges_applied_to',
            field=models.ManyToManyField(through='core.TenantChargePayment', to='core.TenantCharge'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
    ]
