# Generated by Django 3.0.8 on 2020-07-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200710_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantchargepayment',
            old_name='pending_amount',
            new_name='applied_amount',
        ),
    ]
