# Generated by Django 3.0.7 on 2020-06-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200616_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityprovider',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='utilityprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='core.Provider'),
        ),
        migrations.AlterField(
            model_name='utilityprovider',
            name='utility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility', to='core.Utility'),
        ),
    ]
