# Generated by Django 3.0.7 on 2020-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200616_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='utility',
            new_name='utility_provider',
        ),
    ]
