# Generated by Django 3.0.7 on 2020-06-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200617_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityprovider',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AlterField(
            model_name='utilityprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provider'),
        ),
        migrations.AlterField(
            model_name='utilityprovider',
            name='utility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Utility'),
        ),
    ]
