# Generated by Django 3.0.7 on 2020-06-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200617_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='utility_provider',
            new_name='utilities',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='utility_type',
            new_name='type',
        ),
    ]
