# Generated by Django 3.0.7 on 2020-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200622_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
