# Generated by Django 3.0.7 on 2020-06-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200624_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('attribute', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCityUtilityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_units', models.FloatField()),
                ('bill_period_day', models.PositiveIntegerField()),
                ('default_usage', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property')),
                ('utility_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UtilityProvider')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='city_utility',
            field=models.ManyToManyField(through='core.PropertyCityUtilityInfo', to='core.UtilityProvider'),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('installed_date', models.DateField()),
                ('uninstalled_date', models.DateField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Utility')),
            ],
        ),
    ]
