# Generated by Django 3.0.7 on 2020-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200626_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycityutilityinfo',
            name='bill_post_day',
            field=models.PositiveIntegerField(default=8),
            preserve_default=False,
        ),
    ]
