# Generated by Django 3.0.7 on 2020-06-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_propertycityutilityinfo_bill_post_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField()),
                ('amount', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('repair_date', models.DateField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Meter')),
            ],
        ),
    ]
