# Generated by Django 3.0.7 on 2020-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_propertycityutilityinfo_bill_post_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycityutilityinfo',
            name='bill_period_day',
            field=models.PositiveIntegerField(verbose_name=range(1, 31)),
        ),
        migrations.AlterField(
            model_name='propertycityutilityinfo',
            name='bill_post_day',
            field=models.PositiveIntegerField(verbose_name=range(1, 31)),
        ),
    ]
