# Generated by Django 3.0.7 on 2020-06-29 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200629_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycityutilityinfo',
            name='bill_period_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='propertycityutilityinfo',
            name='bill_post_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
