# Generated by Django 3.0.7 on 2020-06-29 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20200629_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='billing_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meter',
            name='installed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meter',
            name='uninstalled_date',
            field=models.DateField(blank=True),
        ),
    ]
