# Generated by Django 3.0.7 on 2020-06-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200629_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='uninstalled_date',
            field=models.DateField(null=True),
        ),
    ]
