# Generated by Django 3.0.7 on 2020-06-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_recollectionfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recollectionfee',
            name='split_method',
        ),
        migrations.AddField(
            model_name='recollectionfee',
            name='usage_based_split',
            field=models.BooleanField(default=False),
        ),
    ]
