# Generated by Django 3.0.7 on 2020-06-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200629_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='uninstalled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
