# Generated by Django 3.0.7 on 2020-06-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200630_1810'),
        ('core', '0018_auto_20200630_0025'),
    ]

    operations = [
    ]
