# Generated by Django 3.0.7 on 2020-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20200630_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='id',
        ),
        migrations.AlterField(
            model_name='utility',
            name='type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
