# Generated by Django 3.0.7 on 2020-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200701_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
