# Generated by Django 3.0.7 on 2020-07-01 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200701_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUtilityProviderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_units', models.FloatField(default=0)),
                ('bill_period_day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('bill_post_day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('default_usage', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='city_utility',
        ),
        migrations.AlterField(
            model_name='metererror',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='metererror',
            name='repair_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterread',
            name='read_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='PropertyCityUtilityInfo',
        ),
        migrations.AddField(
            model_name='propertyutilityproviderinfo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property'),
        ),
        migrations.AddField(
            model_name='propertyutilityproviderinfo',
            name='utility_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UtilityProvider'),
        ),
        migrations.AddField(
            model_name='property',
            name='utility_provider',
            field=models.ManyToManyField(through='core.PropertyUtilityProviderInfo', to='core.UtilityProvider'),
        ),
    ]
