version: "3"

services:
  app:
    build:
      context: ..
      args:
          DEBUG: True
          DB_HOST_ARG: db
          DB_NAME_ARG: local-db
          DB_USER_ARG: local-postgres
          DB_PASS_ARG: local-password
    ports:
      - "8000:8000"
    volumes:
      - ../django-project:/django-project
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=local-db
      - POSTGRES_USER=local-postgres
      - POSTGRES_PASSWORD=local-password
