version: "3"

services:
  nginx:
    build:
      context: ../nginx/
    volumes:
      - static_data:/vol/static
    ports:
      - '8080:8080'
    depends_on:
    - app

  app:
    build:
      context: ..
      args:
          DB_HOST_ARG: ${DB_HOST_ARG}
          DB_NAME_ARG: ${DB_NAME_ARG}
          DB_USER_ARG: ${DB_USER_ARG}
          DB_PASS_ARG: ${DB_PASS_ARG}
          ENV_ARG: local-staging
    volumes:
      - static_data:/vol/web
  #   env_file:
  #     - ../django-project/config/settings/.env
  #   depends_on:
  #     - db
  #
  # db:
  #   image: postgres:10-alpine
  #   environment:
  #     - POSTGRES_DB=local-db
  #     - POSTGRES_USER=local-postgres
  #     - POSTGRES_PASSWORD=local-password

volumes:
  static_data:
