name: Pre-Staging

# only run on pull requests from another branch into staging, not from staging into master
on:
  pull_request:
    branches: [ '!master', '!production', staging ]

jobs:

    build-test-push:

        runs-on: ubuntu-latest

        steps:
        - name: Check out code
          uses: actions/checkout@v2

        # # Build and test the application
        # - name: Build the image and run unit tests
        #   env:
        #     ENV_ARG: staging
        #     SECRET_KEY_ARG: ${{ secrets.DJANGO_SECRET_KEY }}
        #     DB_HOST_ARG: ${{ secrets.STAGING_DB_HOST }}
        #     DB_NAME_ARG: ${{ secrets.STAGING_DB_NAME }}
        #     DB_USER_ARG: ${{ secrets.STAGING_DB_USER }}
        #     DB_PASS_ARG: ${{ secrets.STAGING_DB_PASS }}
        #   run: |
        #     docker-compose -f docker-compose/docker-compose.staging.yml \
        #     run app sh -c "python manage.py test"

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push Docker image of app to Amazon ECR
          id: build-app-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.STAGING_ECR_APP_REPO }}
            IMAGE_TAG: ${{ secrets.STAGING_APP_IMAGE_TAG }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --build-arg ENV_ARG=staging \
            --build-arg SECRET_KEY_ARG=${{ secrets.DJANGO_SECRET_KEY }} \
            --build-arg DB_HOST_ARG=${{ secrets.STAGING_DB_HOST }} \
            --build-arg DB_NAME_ARG=${{ secrets.STAGING_DB_NAME }} \
            --build-arg DB_USER_ARG=${{ secrets.STAGING_DB_USER }} \
            --build-arg DB_PASS_ARG=${{ secrets.STAGING_DB_PASS }} \
            .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        - name: Build, tag, and push Docker image of nginx to Amazon ECR
          id: build-nginx-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.ECR_NGINX_REPO }}
            IMAGE_TAG: ${{ secrets.NGINX_IMAGE_TAG }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./nginx/
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
